### ISSUE TITLE
Simple description of training data requirements

### ISSUE THREAD

**Issue by mrkatey** [kunheek/style-aware-discriminator#1]
Please create a small section in the README that describes in detail the expected format/size etc. for training data including directory structure. I assume it's something like this:
A/
trainA
testA
B/
trainB
testB

images should be of dimension X pixels by Y pixels

**Comment by kunheek** [comment]
Thank you for the suggestion.

If you are going to use images, you can use a variety of formats (jpg, png, etc) and images will be resized using the image_size arguments (e.g., using --image-size=256 will resize images to 256x256).
I've updated the README, so please check it. If you have further questions, please let me know.

**Comment by mrkatey** [comment]
Thank you!
