### ISSUE TITLE
Sample code for image translation

### ISSUE THREAD

**Issue by laxmimerit** [kunheek/style-aware-discriminator#3]
Hi,
Can you please share a sample code to translate `img_src.jpg` with `img_reference.jpg`. This seems very interesting project. Just wanna have some fun with this :)

**Comment by kunheek** [comment]
Hi,
You can translate a single image using the `python -m synthesis swap` command. Assume that your images are stored as below:
```sh
./testphotos
├─ content
│  └─ img_src.jpg
└─ style
   └─ img_reference.jpg
```
You can translate `img_src.jpg` with `img_reference.jpg` using the following command:
```sh
python -m synthesis swap --checkpoint checkpoints/afhq-stylegan2-5M.pt --folder testphotos/content testphotos/style/ --save-each true
```

Let me know if you have any other questions!
