### ISSUE TITLE
训练的epoch

### ISSUE THREAD

**Issue by zi1zi** [kunheek/style-aware-discriminator#5]
我跑了一下代码，那个训练轮数在哪里设置，为啥我感觉只有一轮就结束了

**Comment by kunheek** [comment]
Hi.
Again, I am not sure if I understand your question correctly (I don't speak Chinese 😢).
According to the Google translate, your question is:
`I ran the code, where is the number of training rounds set, why do I feel that it is over after only one round.`

Training iteration is decided by number of total images (`--total-nimg`) and batch size (`--batch-size`). The training step will be repeated for total_nimg/batch_size iterations.

**Comment by zi1zi** [comment]
您好，您拿谷歌翻译就很好的交流哈，我想用我自己的数据集来跑代码，我的数据集是八百张字体图片，bath_size大小为4，所以是200iter就结束了，感觉像是1个epoch

**Comment by kunheek** [comment]
Did you modified dataset part?
If so, you have to wrap your dataset implementation with [`DataPipe`](https://github.com/kunheek/style-aware-discriminator/blob/f3c158a4d7032e7be600bdbff42b543175eae20c/data.py#L63). Then it loops infinitely.

**Comment by zi1zi** [comment]
您好，我没有改动任何代码，只是想用自己的数据集进行训练，必须用DataPipe吗

**Comment by zi1zi** [comment]
同时想咨询一下具体的用法

**Comment by kunheek** [comment]
`DataPipe` will be used by default. Then, all you need to do is point `--train-dataset` to your dataset. For example, you can use the command like this:
```bash
python train.py --train-dataset PATH/TO/DATASET --eval-dataset PATH/TO/DATASET
```

**Comment by zi1zi** [comment]
![image](https://user-images.githubusercontent.com/48040139/197426944-012bbd71-c9e1-47a1-bfc9-7bc7ab055df5.png)
您好，我一直使用的是这条命令，但是没有无限循环，无限循环是需要额外改动代码吗，如果需要修改，具体该如何修改

**Comment by kunheek** [comment]
Hello.
You have to set `--total-nimg` larger than 800. In your case, training iteration will be 800/4 (`--total-nimg`/`--batch-size`). The default `--total-nimg` will be enough, so you you can just leave `--total-nimg` as default. Try to use this command:
```bash
python train.py --mod-type again --batch-size 4 --train-dataset datasets/train --eval-dataset datasets/val
```

By the way, if you have enough GPU memory, try batch size larger than 16. I guess batch size 4 may not work.

**Comment by zi1zi** [comment]
谢谢您的及时答复，我还是有一点疑问，--total-nimg是总图片的数量吗，但是我的总图片数量只有八百，总图片数量默认5M的话，是不是将八百张图片进行5M/800个epoch

**Comment by kunheek** [comment]
`--total-nimg` means the total number of real images that discriminator sees during the training. There is no need to set it to 5M/800 as it is completely independent of the number of training images.

**Comment by zi1zi** [comment]
那您代码epoch如何计算，就是模型把八百张图片跑了几轮，您的iter ==--total-nimg/ --batch-size 不是特别懂这个公式

**Comment by kunheek** [comment]
We don't use the concept of traditional epochs in this project. However, if you want to train your model for specific epochs, you can calculate it by `epochs = total_nimg / (batch_size * number_of_your_images)`. In your case, you can set `total_nimg` as `epochs * batch_size * number_of_your images` = `epochs * 4 * 800`.

**Comment by zi1zi** [comment]
您好，训练好模型以后，如何测试我的模型

**Comment by kunheek** [comment]
Please refer to the README.md for basic evaluation. For more complex scenarios, you'll have to write your own.

**Comment by zi1zi** [comment]
您好，我参考readme.md进行定量评估时出现了如下错误 raise ValueError ValueError，使用的命令是 python -m metrics fid reconstruction --seed 123 --checkpoint ./checkpoints/networks-00080k.pt --train-dataset ./datasets/train --eval-dataset ./datasets/val
在进行定性评估时出现了显存不足，请问调节哪个参数可以使程序使用的显存没有那么大(我的显存是11G)，使用的命令是python -m synthesis swap --checkpoint ./checkpoints/networks-00080k.pt  --folder ./datasets/train/id_0  ./datasets/train/id_1

**Comment by kunheek** [comment]
**I have the following error raise ValueError:**
FID evaluation only supports these datasets: AFHQ, CelebA-HQ, LSUN church, FFHQ. You should modify the `metrics/fid_evaluation.py` to compute FID for other datasets.

**There is insufficient video memory during qualitative evaluation:**
Swap synthesis translates all images in the folder. You can reduce the images in the folder.

**Comment by zi1zi** [comment]
python -m tools.plot_tsne --checkpoint checkpoints/afhq-stylegan2-5M.pt --target-dataset datasets/afhq/val --seed 7 --title AFHQ --legends cat dog wild 执行这个命令时，--legends无法识别

python -m tools.similarity_search --checkpoint CKPT --query QUERY_IMAGE --target-dataset TESTDIR
执行这个命令时，--query QUERY_IMAGE 后面具体参数应该写啥呢，一张图片的话不太可以

**Comment by kunheek** [comment]
Sorry for the inconvenience.
This is a research project and most of the code was optimized for public datasets. For more general cases, I recommend you to customize yourself.

**Comment by zi1zi** [comment]
--load-size 320 --crop-size 256 --image-size 80 这三个参数分别代表什么意义呀，如果图片大小都是80，这三个参数都设置80有影响吗

**Comment by zi1zi** [comment]
您的上一个解释我不是很理解，--legends 这个参数 plot_tsne.py文件就无法接受这个参数，plot_tsne.py代码中出现legends的地方为    legends = len(np.unique(targets)) == len(labels)

**Comment by kunheek** [comment]
See [model/augmentation.py](https://github.com/kunheek/style-aware-discriminator/blob/main/model/augmentation.py) to understand how these arguments (`--load-size` and `--crop-size`) work. `--image-size` is used to determine the network architecture.
Also, I have corrected the wrong command, so please check it. You can parse `--labels` instead of `--legends`. But, still I cannot guarantee this will work in your situation since it is designed for AFHQ and CelebA-HQ folder structure.

**Comment by zi1zi** [comment]
您好，在训练中出现如下错误
Generating images for HYCuFangSongJ2HYBeiKeHeiW...

 29%|██▊       | 19999/70000 [15:37:46<39:04:35,  2.81s/it]
downloading statistics to /home /.conda/envs/style-aware/lib/python3.8/site-packages/cleanfid/stats/datasets_hybeikeheiw256_clean_custom_na.npz
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    main()
  File "train.py", line 237, in main
    training_loop(model, option, rank, world_size)
  File "train.py", line 177, in training_loop
    fid_dict = mfid_evaluator.evaluate(model)
  File "/home /.conda/envs/style-aware/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home /code/style-aware-discriminator/metrics/mean_fid_evaluator.py", line 118, in evaluate
    results_dict["FID_"+task["name"]] = fid.compute_fid(
  File "/home /.conda/envs/style-aware/lib/python3.8/site-packages/cleanfid/fid.py", line 431, in compute_fid
    score = fid_folder(fdir1, dataset_name, dataset_res, dataset_split,
  File "/home /.conda/envs/style-aware/lib/python3.8/site-packages/cleanfid/fid.py", line 178, in fid_folder
    ref_mu, ref_sigma = get_reference_statistics(dataset_name, dataset_res,
  File "/home /.conda/envs/style-aware/lib/python3.8/site-packages/cleanfid/features.py", line 56, in get_reference_statistics
    fpath = check_download_url(local_folder=stats_folder, url=url)
  File "/home /.conda/envs/style-aware/lib/python3.8/site-packages/cleanfid/downloads_helper.py", line 36, in check_download_url
    with urllib.request.urlopen(url) as response, open(local_path, 'wb') as f:
  File "/home /.conda/envs/style-aware/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home /.conda/envs/style-aware/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home /.conda/envs/style-aware/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home /.conda/envs/style-aware/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home /.conda/envs/style-aware/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home /.conda/envs/style-aware/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by kunheek** [comment]
It's probably because you're trying to download unsupported FID stat from `clean-fid`. This shouldn't happen because it's prevented in code. I think it's because you either modified the code or deleted FID stats. As mentioned before, evaluation of custom datasets is difficult to help.

**Comment by zi1zi** [comment]
您好，我又跑了一次模型，但是还是上次的错误，我并没有改动代码

**Comment by kunheek** [comment]
If evaluation is a problem, you can train networks without evaluation by adding `--evaluation false` to the command.

**Comment by zi1zi** [comment]
![lerp0_0](https://user-images.githubusercontent.com/48040139/200096959-f104cb11-b0e5-4890-8f59-20a5e020fe26.png)
这是snapshot文件夹中040k lerp0_0.png
![lerp0_0](https://user-images.githubusercontent.com/48040139/200096979-5b46ee1b-833e-4e87-8caa-e5e471553550.png)
这是snapshot文件夹中045k lerp0_0.png
045k之后的图片全部为黑色，请问这是怎么回事呢

**Comment by kunheek** [comment]
I think the model had failed to converge. GAN training is notoriously unstable, and small changes cause the failure (e.g., quality/quantity of dataset or hyperparameters). [This article](https://neptune.ai/blog/gan-failure-modes) may help you.
